(function () {
    function Sa(d) { d = ("; " + document.cookie).split("; " + d + "="); return 2 == d.length ? Fa(d.pop().split(";").shift()) : "" } function Eb(d, l, y) { var h = document.domain.split("."); if (1 < h.length && l) for (var w = "." + h[h.length - 1], A = h.length - 2; 0 <= A; A--) { w = "." + h[A] + w; var p = void 0, r = d, m = l, u = y, B = w; u && (p = new Date, p.setTime(p.getTime() + 1E3 * u)); document.cookie = r + "=" + Ka(m) + (u ? ";expires=" + p.toGMTString() : "") + ";path=/" + (B ? ";domain=" + B : ""); if (Sa(d) == l) break } } function Ga(d) {
        if (!Ha) return !1; d = "" + Fa(window.localStorage.getItem(d));
        d = d.split(";ex="); if (2 == d.length) if (0 < d[1]) { var l = new Date; l = l.valueOf(); if (l <= d[1]) return d[0] } else return d[0]; return ""
    } function Ia(d, l, y) { if (!Ha) return !1; var h = 0; y && (h = new Date, h.setTime(h.getTime() + 1E3 * y), h = h.valueOf()); window.localStorage.setItem(d, Ka(l + ";ex=" + h)) } function gb(d, l, y) {
        var h = document.createElement("script"); h.src = d; h.async = !0; h.onreadystatechange = h.onload = function () { var w = h.readyState; l.done || w && !/loaded|complete/.test(w) || (l.done = !0, l()) }; h.onerror = function () {
            y.done || (y.done = !0,
                y())
        }; document.getElementsByTagName("head")[0].appendChild(h)
    } function Fb() { for (var d = "", l = 0; 16 > l; l++)d += "abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(36 * Math.random())); l = /Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|NetFront|Silk-Accelerated|(hpw|web)OS|Fennec|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Dolphin|Skyfire|Zune/i.test(hb) ? "mob" : Ta("iPad") || Ta("Android") && !Ta("Mobile") || Ta("Silk") ? "tab" : "des"; return d + "." + Math.floor((new Date).getTime() / 1E3) + "." + l } function Gb(d) {
        this.fosp_aid =
        d; this.fosp_loc = ""; var l = document, y = window.encodeURIComponent; this.getCookie = function (h) { return (cookieMatch = RegExp("(^|;)[ ]*" + h + "=([^;]*)").exec(l.cookie)) ? Ka(cookieMatch[2]) : "" }; this.getMeta = function (h) { var w = document.getElementsByTagName("meta"); if (0 < w.length) for (var A = 0; A < w.length; A++)if (null != w[A].getAttribute("name") && w[A].getAttribute("name").toLowerCase() == h.toLowerCase()) return w[A].getAttribute("content"); return !1 }; this.logData = function (h) {
            try {
                for (var w = "net com edu org gov biz info".split(" "),
                    A = 0, p = w.length; A < p; ++A)w.push(w[A] + "\\.vn"); w.push("vn"); w.push("us"); var r = RegExp("(\\.?[^.]+\\.(" + w.join("|") + ")$)"), m = document.domain.match(r), u; null !== m ? u = m[1] : (m = document.domain.match(/(\.?[^.]+\.?[^.]+$)/), null !== m && (u = m[1])); "." == u[0] && (u = u.substr(1)); var B = (v = /(^|&)[ ]*fosp_aid=([^&]*)/.exec(window.name)) ? window.decodeURIComponent(v[2]) : this.fosp_aid; y = this.getCookie("myvne_user_id") || B || this.fosp_aid; _paq.push(["setTrackerUrl", "//la.vnecdn.net/get"]); _paq.push(["setSiteId", h]); _paq.push(["setFospId",
                        y]); _paq.push(["setLocation", this.fosp_loc]); var t = this.getMeta("keywords"), G = this.getMeta("description"), I = this.getMeta("tt_category_id"); if (0 != I) { _paq.push(["setCustomVariable", "2", "tt_category_id", I, "page"]); var n = this.getMeta("tt_article_id"); 0 != n && _paq.push(["setCustomVariable", "3", "tt_article_id", n, "page"]) } _paq.push(["setCustomVariable", "4", "fosp_aid", y, "visit"]); var x = this.getCookie("CPMS_LOG"); null !== x && 0 != x && _paq.push(["setCustomVariable", "5", "CPMS_LOG", x, "visit"]); _paq.push(["setCustomVariable",
                            "6", "keyword", t + " " + G, "page"]); if ("undefined" !== typeof Storage) try { var D = window.localStorage.eatv, H = window.localStorage.fosp_session; _paq.push(["setCustomVariable", "7", "fosp_aid_bk", B, "visit"]); _paq.push(["setCustomVariable", "8", "eatv", D, "visit"]); _paq.push(["setCustomVariable", "9", "fosp_session", H, "visit"]); _paq.push(["setCustomVariable", "10", "fosp_gender", 0, "visit"]) } catch (S) { } _paq.push(["setDocumentTitle", document.domain + "/" + document.title]); _paq.push(["setCookieDomain", "*." + u]); PiwikNew.getAsyncTracker().trackPageView()
            } catch (S) { }
        }
    }
    var Ka = function (d) { try { return "function" == typeof encodeURIComponent ? encodeURIComponent(d) : escape(d) } catch (l) { return d } }, Fa = function (d) { try { return "function" == typeof decodeURIComponent ? decodeURIComponent(d) : unescape(d) } catch (l) { return d } }, Zb = window.encodeURIComponent, $b = unescape, Ua = function (d) {
        var l = function (H, S) { return H << S | H >>> 32 - S }, y = function (H) { var S = "", Z; for (Z = 7; 0 <= Z; Z--)S += (H >>> 4 * Z & 15).toString(16); return S }, h, w = [], A = 1732584193, p = 4023233417, r = 2562383102, m = 271733878, u = 3285377520, B = []; d = $b(Zb(d));
        var t = d.length; for (h = 0; h < t - 3; h += 4) { var G = d.charCodeAt(h) << 24 | d.charCodeAt(h + 1) << 16 | d.charCodeAt(h + 2) << 8 | d.charCodeAt(h + 3); B.push(G) } switch (t & 3) { case 0: h = 2147483648; break; case 1: h = d.charCodeAt(t - 1) << 24 | 8388608; break; case 2: h = d.charCodeAt(t - 2) << 24 | d.charCodeAt(t - 1) << 16 | 32768; break; case 3: h = d.charCodeAt(t - 3) << 24 | d.charCodeAt(t - 2) << 16 | d.charCodeAt(t - 1) << 8 | 128 }for (B.push(h); 14 !== (B.length & 15);)B.push(0); B.push(t >>> 29); B.push(t << 3 & 4294967295); for (d = 0; d < B.length; d += 16) {
            for (h = 0; 16 > h; h++)w[h] = B[d + h]; for (h =
                16; 79 >= h; h++)w[h] = l(w[h - 3] ^ w[h - 8] ^ w[h - 14] ^ w[h - 16], 1); G = A; t = p; var I = r, n = m, x = u; for (h = 0; 19 >= h; h++) { var D = l(G, 5) + (t & I | ~t & n) + x + w[h] + 1518500249 & 4294967295; x = n; n = I; I = l(t, 30); t = G; G = D } for (h = 20; 39 >= h; h++)D = l(G, 5) + (t ^ I ^ n) + x + w[h] + 1859775393 & 4294967295, x = n, n = I, I = l(t, 30), t = G, G = D; for (h = 40; 59 >= h; h++)D = l(G, 5) + (t & I | t & n | I & n) + x + w[h] + 2400959708 & 4294967295, x = n, n = I, I = l(t, 30), t = G, G = D; for (h = 60; 79 >= h; h++)D = l(G, 5) + (t ^ I ^ n) + x + w[h] + 3395469782 & 4294967295, x = n, n = I, I = l(t, 30), t = G, G = D; A = A + G & 4294967295; p = p + t & 4294967295; r = r + I & 4294967295;
            m = m + n & 4294967295; u = u + x & 4294967295
        } D = y(A) + y(p) + y(r) + y(m) + y(u); return D.toLowerCase()
    }, ib = Ua(Math.random() + function (d) { for (var l = "", y = 0; y < d; y++)l += "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62 * Math.random())); return l }(10) + Date.now()).substr(0, 32); window.la_pageview_id = ib; var hb = ""; var ja = window.navigator; hb = ja && (ja = ja.userAgent) ? ja : ""; var Ta = function (d) { return -1 !== hb.toLowerCase().indexOf(d.toLowerCase()) }; "object" !== typeof JSON2 && (JSON2 = {}); var ac = window.adblock ||
        0, Ha = window.localStorage && "function" == typeof window.localStorage.setItem ? 1 : 0; (function () {
            function d(u) { return 10 > u ? "0" + u : u } function l(u) { w.lastIndex = 0; return w.test(u) ? '"' + u.replace(w, function (B) { var t = r[B]; return "string" === typeof t ? t : "\\u" + ("0000" + B.charCodeAt(0).toString(16)).slice(-4) }) + '"' : '"' + u + '"' } function y(u, B) {
                var t, G, I, n = A, x = B[u]; x && "object" === typeof x && (t = x, I = Object.prototype.toString.apply(t), x = "[object Date]" === I ? isFinite(t.valueOf()) ? t.getUTCFullYear() + "-" + d(t.getUTCMonth() + 1) + "-" + d(t.getUTCDate()) +
                    "T" + d(t.getUTCHours()) + ":" + d(t.getUTCMinutes()) + ":" + d(t.getUTCSeconds()) + "Z" : null : "[object String]" === I || "[object Number]" === I || "[object Boolean]" === I ? t.valueOf() : "[object Array]" !== I && "function" === typeof t.toJSON ? t.toJSON(u) : t); "function" === typeof m && (x = m.call(B, u, x)); switch (typeof x) {
                        case "string": return l(x); case "number": return isFinite(x) ? String(x) : "null"; case "boolean": case "null": return String(x); case "object": if (!x) return "null"; A += p; var D = []; if ("[object Array]" === Object.prototype.toString.apply(x)) {
                            var H =
                                x.length; for (t = 0; t < H; t += 1)D[t] = y(t, x) || "null"; I = 0 === D.length ? "[]" : A ? "[\n" + A + D.join(",\n" + A) + "\n" + n + "]" : "[" + D.join(",") + "]"; A = n; return I
                        } if (m && "object" === typeof m) for (H = m.length, t = 0; t < H; t += 1)"string" === typeof m[t] && (G = m[t], (I = y(G, x)) && D.push(l(G) + (A ? ": " : ":") + I)); else for (G in x) Object.prototype.hasOwnProperty.call(x, G) && (I = y(G, x)) && D.push(l(G) + (A ? ": " : ":") + I); I = 0 === D.length ? "{}" : A ? "{\n" + A + D.join(",\n" + A) + "\n" + n + "}" : "{" + D.join(",") + "}"; A = n; return I
                    }
            } var h = RegExp("[\x00\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]",
                "g"), w = RegExp('[\\\\\\"\x00-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]', "g"), A, p, r = { "\b": "\\b", "\t": "\\t", "\n": "\\n", "\f": "\\f", "\r": "\\r", '"': '\\"', "\\": "\\\\" }, m; "function" !== typeof JSON2.stringify && (JSON2.stringify = function (u, B, t) {
                    var G; p = A = ""; if ("number" === typeof t) for (G = 0; G < t; G += 1)p += " "; else "string" === typeof t && (p = t); if ((m = B) && "function" !== typeof B && ("object" !== typeof B || "number" !== typeof B.length)) throw Error("JSON2.stringify");
                    return y("", { "": u })
                }); "function" !== typeof JSON2.parse && (JSON2.parse = function (u, B) {
                    function t(I, n) { var x, D, H = I[n]; if (H && "object" === typeof H) for (x in H) Object.prototype.hasOwnProperty.call(H, x) && (D = t(H, x), void 0 !== D ? H[x] = D : delete H[x]); return B.call(I, n, H) } var G; u = String(u); h.lastIndex = 0; h.test(u) && (u = u.replace(h, function (I) { return "\\u" + ("0000" + I.charCodeAt(0).toString(16)).slice(-4) })); if (/^[\],:{}\s]*$/.test(u.replace(RegExp('\\\\(?:["\\\\/bfnrt]|u[0-9a-fA-F]{4})', "g"), "@").replace(RegExp('"[^"\\\\\n\r]*"|true|false|null|-?\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d+)?',
                        "g"), "]").replace(RegExp("(?:^|:|,)(?:\\s*\\[)+", "g"), ""))) return G = eval("(" + u + ")"), "function" === typeof B ? t({ "": G }, "") : G; throw new SyntaxError("JSON2.parse");
                })
        })(); ja = new function () {
            var d = document, l = window, y = "---", h = function (p, r, m) { return p.call.apply(p.bind, arguments) }, w = function (p, r, m) {
                if (!p) throw Error(); if (2 < arguments.length) { var u = Array.prototype.slice.call(arguments, 2); return function () { var B = Array.prototype.slice.call(arguments); Array.prototype.unshift.apply(B, u); return p.apply(r, B) } } return function () {
                    return p.apply(r,
                        arguments)
                }
            }, A = function (p, r, m) { A = Function.prototype.bind && -1 != Function.prototype.bind.toString().indexOf("native code") ? h : w; return A.apply(null, arguments) }; this._userNew = Fb(); this.setCookie = function (p, r, m, u, B, t) { var G; m && (G = new Date, G.setTime(G.getTime() + 1E3 * m)); d.cookie = p + "=" + Ka(r) + (m ? ";expires=" + G.toGMTString() : "") + ";path=" + (u || "/") + (B ? ";domain=" + B : "") + (t ? ";secure" : "") }; this.getCookie = function (p) { return (cookieMatch = RegExp("(^|;)[ ]*" + p + "=([^;]*)").exec(d.cookie)) ? Fa(cookieMatch[2]) : "" }; this.getFospAll =
                function (p) { var r = this.getCookie(p) || "", m = (new RegExp("(^|&)[ ]*" + p + "=([^&]*)", "i")).exec(l.name); m = m && 2 < m.length && Fa(m[2]) || ""; p = Ga(p); return r = (r = m || r || p) && r.replace(/[^a-zA-Z0-9\.]+/g, "") }; this.syncUser = function (p) {
                    var r = p.origin || p.originalEvent.origin; try { var m = JSON.parse(p.data) } catch (u) { m = {} } m.id && "sync_user" == m.id && m.type && (m = { id: "sync_user_reply", fosp_aid: this.fosp_aid, orig_aid: this.orig_aid, myvne_user_id: parseInt("0" + this.getCookie("myvne_user_id")) || 0 }, p.source && p.source.postMessage(JSON.stringify(m),
                        r))
                }; this.setStringForm = function (p, r, m) { m = Ka(m); if (-1 < p.indexOf("&" + r + "=") || 0 === p.indexOf(r + "=")) { var u = p.indexOf("&" + r + "="); -1 === u && (u = p.indexOf(r + "=")); var B = p.indexOf("&", u + 1); return -1 !== B ? p.substr(0, u) + p.substr(B + (u ? 0 : 1)) + "&" + r + "=" + m : p.substr(0, u) + "&" + r + "=" + m } return p + "&" + r + "=" + m }; this.writeCookieByDomain = function (p, r) {
                    if ("string" == typeof r) {
                        r = r.replaceAll('"', ""); var m = d.domain.split("."); if (1 < m.length && r) for (var u = "." + m[m.length - 1], B = m.length - 2; 0 <= B && (u = "." + m[B] + u, this.setCookie(p, r, 31449600,
                            "/", u), this.getCookie(p) != r); B--); l.name = this.setStringForm(l.name, p, r); Ia(p, r, 0); "fosp_aid" == p ? this.fosp_aid = r : "orig_aid" == p && (this.orig_aid = r)
                    }
                }; this.workerCookies = function (p) {
                    if (d.cookie != y || 2 == p) {
                        y = d.cookie; p = parseInt("0" + this.getCookie("myvne_user_id")) || 0; var r = this.getFospAll("fosp_aid") || "", m = this.getFospAll("orig_aid") || "", u = 0; if (1E6 <= p) p = "" + p, r != p ? (u = 1, this.writeCookieByDomain("fosp_aid", p), r != m && (15 < r.length && 35 > r.length ? m = r : 16 > m.length && (m = this._userNew), this.writeCookieByDomain("orig_aid",
                            m))) : 16 > m.length && (m = this._userNew, u = 1, this.writeCookieByDomain("orig_aid", m)), r = p; else { var B = r, t = m; if (15 > r.length || 35 < r.length) u = 1, B = 15 < m.length && 35 > m.length ? m : t = this._userNew; else if (15 > m.length || 35 < m.length) t = r; B != r && (r = B, this.writeCookieByDomain("fosp_aid", r)); t != m && (m = t, this.writeCookieByDomain("orig_aid", m)) } r != this.getCookie("fosp_aid") && (u = 1, this.writeCookieByDomain("fosp_aid", r)); m != this.getCookie("orig_aid") && (u = 1, this.writeCookieByDomain("orig_aid", m)); 1 == u && (p = "https://adp.vnecdn.net/syncuser?" +
                                ["fosp_aid=" + r, "orig_aid=" + m, "myvne_user_id=" + p].join("&"), this.xhr(p, A(this.setUser, this)))
                    }
                }; this.xhr = function (p, r) { var m = new XMLHttpRequest; m.withCredentials = !0; m.crossDomain = !0; m.onreadystatechange = function () { 4 === m.readyState && r(m.response) }; m.open("GET", p, !0); m.send("") }; this.setUser = function (p) {
                    if ("" != p) {
                        var r = {}; try { try { r = JSON.parse(p), r = r.data || {} } catch (m) { r = {} } } catch (m) { } r && (r.fosp_aid && 9 < r.fosp_aid.length && 35 > r.fosp_aid.length && this.writeCookieByDomain("fosp_aid", r.fosp_aid), r.orig_aid &&
                            15 < r.orig_aid.length && 35 > r.orig_aid.length && this.writeCookieByDomain("orig_aid", r.orig_aid))
                    }
                }; this.pushUser = function () { if (l.JSON && l.postMessage) { var p = A(this.syncUser, this); l.addEventListener ? l.addEventListener("message", p, !1) : l.attachEvent && l.attachEvent("onmessage", p) } }; this.fosp_aid = this.getFospAll("fosp_aid"); this.orig_aid = this.getFospAll("orig_aid"); l.setInterval(A(this.workerCookies, this), 3E3); this.workerCookies(2); this.pushUser()
        }; ja = ja.fosp_aid || ja.orig_aid || Fb(); "object" !== typeof _paq &&
            (_paq = []); (function () {
                var d = document, l = window, y = window._logAdp || (window._logAdp = []); if (y.push === Array.prototype.push) {
                    var h = 0, w = l.localStorage && "function" == typeof l.localStorage.setItem ? 1 : 0, A = function (n) {
                        switch (Object.prototype.toString.call(n)) { case "[object Date]": return "date"; case "[object RegExp]": return "regexp"; case "[object Arguments]": return "arguments"; case "[object Array]": return "array"; case "[object Error]": return "error" }if (null === n) return "null"; if (void 0 === n) return "undefined"; if (n !== n) return "nan";
                        if (n && 1 === n.nodeType) return "element"; n = n.valueOf ? n.valueOf() : Object.prototype.valueOf.apply(n); return typeof n
                    }, p = /(\w+)\[(\d+)\]/, r = function (n) { try { return encodeURIComponent(n) } catch (x) { return n } }, m = function (n) { try { return decodeURIComponent(n.replace(/\+/g, " ")) } catch (x) { return n } }, u = [], B = function () {
                        gb("https://la2.vnecdn.net/static/device_model_min.js", function () {
                            try {
                                var n = (new DeviceModelParser).getResult(); Ia("la2_device_model", JSON.stringify(n)); if ("object" == typeof n) for (var x in n) {
                                    var D = n[x].code ||
                                        ""; "" != D && u.push(D)
                                }
                            } catch (H) { }
                        })
                    }, t = new function () {
                        this.ss_id = 0; this.pageview_id = ib; this.getSS = function () { var n = 0, x = Math.floor((new Date).getTime() / 1E3); if (!w) return n; var D = Ga("la2_ss"); if ("" != D && null != D) { var H = D.split(":"); 1 < H.length && (D = parseInt(H[1], 10), H = parseInt(H[0], 10), 1E6 <= H && 9E6 >= H && 100 < D && D >= x - 1800 && (n = H)) } if (1E6 > n || 9E6 < n) n = Math.floor(8000001 * Math.random()) + 1E6; Ia("la2_ss", n + ":" + x); return n }; this.a = function (n) { return (n = (new RegExp("(^|;)[ ]*" + n + "=([^;]*)")).exec(d.cookie)) ? Fa(n[2]) : "" };
                        this.debug = function (n) { l.console && l.console.log(n) }; this.b = function (n) { var x = d.getElementsByTagName("meta"); if (0 < x.length) for (var D = 0; D < x.length; D++)if (null != x[D].getAttribute("name") && x[D].getAttribute("name").toLowerCase() == n.toLowerCase()) return x[D].getAttribute("content"); return "" }; this.M = function (n) { return null === n ? !1 : "function" === typeof n || "object" === typeof n }; this.parseQuery = function (n) {
                            if ("string" != typeof n) return {}; n = n.replace(/^\s*|\s*$/g, ""); if ("" == n) return {}; "?" == n.charAt(0) && (n = n.slice(1));
                            var x = {}; n = n.split("&"); for (var D = 0; D < n.length; D++) { var H = n[D].split("="); var S = m(H[0]); (S = p.exec(S)) ? (x[S[1]] = x[S[1]] || [], x[S[1]][S[2]] = m(H[1])) : x[H[0]] = null == H[1] ? "" : m(H[1]) } return x
                        }; this.f = function (n) {
                            if (n.hasOwnProperty("action")) if (h && "pv" == n.action) h = 1; else {
                                0 == this.ss_id && (this.ss_id = this.getSS()); var x = this.a("fosp_location_zone"), D = this.a("fosp_country"), H = this.a("fosp_isp"), S = this.a("fosp_location"), Z = this.b("tt_site_id_new"), wa = this.b("tt_page_type_new"), L = this.b("tt_site_id"), V = this.b("tt_page_type"),
                                    ha = this.b("tt_category_id"), J = this.b("tt_article_id"), ba = this.b("tt_list_folder"), ka = this.b("its_publication"), za = this.b("its_author"), T = this.b("its_type"), Aa = this.b("its_wordcount"), la = ((this.a("fosp_aid") || (WNMatch = /(^|&)[ ]*fosp_aid=([^&]*)/.exec(l.name)) && Fa(WNMatch[2])) + "").replace(/"|'/g, "").substr(0, 40), K = this.a("fosp_gender"), ra = this.a("fosp_ip"), X = parseInt(this.a("myvne_user_id")), k = this.a("orig_aid"), F = "", b = "", c = "", g = "", z = "", f = l.location.href.split("#")[0].split("?"), N = "", C = "", R = "", ia = "",
                                    ca = ""; 1 < f.length && (f = this.parseQuery(f[1]), f.utm_source && "" != f.utm_source && (N = f.utm_source), f.utm_medium && "" != f.utm_medium && (R = f.utm_medium), f.utm_campaign && "" != f.utm_campaign && (C = f.utm_campaign), f.utm_term && "" != f.utm_term && (ia = f.utm_term), f.utm_content && "" != f.utm_content && (ca = f.utm_content)); var W = 0, sa = 0, ta = ""; if ("object" == typeof l.dataLayer) for (f = 0; f < l.dataLayer.length; f++) {
                                        var U = l.dataLayer[f]; for (M in U) "TaxonomyIndexType" == M && "" != U[M] && (ta = U[M]), "TaxonomySubTopicId" == M && "" != U[M] && (W = U[M]), "TaxonomyIndexFormatId" ==
                                            M && "" != U[M] && (sa = U[M]), "vn_source" == M && "" != U[M] && (F = U[M]), "vn_campaign" == M && "" != U[M] && (b = U[M]), "vn_medium" == M && "" != U[M] && (c = U[M]), "vn_term" == M && "" != U[M] && (g = U[M]), "vn_content" == M && "" != U[M] && (z = U[M])
                                    } if (10 > k.length || 40 < k.length) k = la; "" == this.pageview_id && (this.pageview_id = ib); var M = this.ss_id; f = this.pageview_id; U = d.referrer; var Va = l.location.href; if (!(0 < u.length)) {
                                        var ua = Ga("la2_device_model"); ua = "" != ua && JSON.parse(ua); if ("object" == typeof ua && 0 < ua.length) for (va in 7 <= Math.floor(10 * Math.random()) &&
                                            l.setTimeout(B, 3E3), ua) { var La = ua[va].code || ""; "" != La && u.push(La) } else B()
                                    } var va = u.join("/"); x = {
                                        app_id: 100, ss_id: M, pg_id: f, site_id: Z, page_type: wa, idsite: L, type: V, fid: ha, aid: J, fosp_aid: la, orig_aid: k, fosp_country: D, fosp_gender: K, fosp_ip: ra, fosp_isp: H, fosp_zone: x, fosp_location: S, adblock: 1 == ac ? 1 : 0, myvne_user_id: 0 < X ? X : 0, referrer: U, url: Va, publication: ka, author: za, article_type: T, wordcount: Aa, list_folder: ba, vn_source: F, vn_medium: c, vn_campaign: b, vn_term: g, vn_content: z, utm_source: N, utm_medium: R, utm_campaign: C,
                                        utm_term: ia, utm_content: ca, index_topic: W, index_format: sa, index_type: ta, dm: va, r: Math.random(), v: "0707"
                                    }; for (var ma in n) x[ma] = n[ma]; n = "pv" == n.action ? "get" : "adp"; if (x) { ma = []; for (na in x) if (D = x[na], "array" != A(D)) ma.push(r(na) + "=" + r(x[na])); else for (H = 0; H < D.length; ++H)ma.push(r(na + "[" + H + "]") + "=" + r(D[H])); var na = ma.join("&") } else na = ""; n = "https://la2.vnecdn.net/" + n + "?" + na; document.createElement("img").src = n
                            }
                        }
                    }; t.f({ action: "pv" }); if (y.push === Array.prototype.push) {
                        for (var G = 0, I = y.length; G < I; ++G)t.f(y[G]);
                        y.push = function (n) { t.f(n) }
                    }
                }
            })(); "object" !== typeof PiwikNew && (PiwikNew = function () {
                function d(k) { return "undefined" !== typeof k } function l(k) { return "object" === typeof k } function y(k) { return "string" === typeof k || k instanceof String } function h() { var k; for (k = 0; k < arguments.length; k += 1) { var F = arguments[k], b = F.shift(); y(b) ? ra[b].apply(ra, F) : b.apply(ra, F) } } function w(k, F, b, c) { if (k.addEventListener) return k.addEventListener(F, b, c), !0; if (k.attachEvent) return k.attachEvent("on" + F, b); k["on" + F] = b } function A(k, F) {
                    var b =
                        "", c, g; for (c in wa) Object.prototype.hasOwnProperty.call(wa, c) && (g = wa[c][k], "function" === typeof g && (b += g(F))); return b
                } function p() { var k; if (!ka) for (ka = !0, A("load"), k = 0; k < za.length; k++)za[k](); return !0 } function r(k, F) { var b = L.createElement("script"); b.type = "text/javascript"; b.src = k; b.readyState ? b.onreadystatechange = function () { var c = this.readyState; if ("loaded" === c || "complete" === c) b.onreadystatechange = null, F() } : b.onload = F; L.getElementsByTagName("head")[0].appendChild(b) } function m() {
                    var k = ""; try { k = J.top.document.referrer } catch (F) {
                        if (J.parent) try {
                            k =
                            J.parent.document.referrer
                        } catch (b) { k = "" }
                    } "" === k && (k = L.referrer); return k
                } function u(k) { return (k = /^([a-z]+):/.exec(k)) ? k[1] : null } function B(k) { var F = /^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(k); return F ? F[1] : k } function t(k, F) { var b = RegExp("[\\?&#]" + F + "=([^&#]*)").exec(k); return b ? Aa(b[1]) : "" } function G(k, F, b) {
                    if ("translate.googleusercontent.com" === k) "" === b && (b = F), F = t(F, "u"), k = B(F); else if ("cc.bingj.com" === k || "webcache.googleusercontent.com" === k || "74.6." === k.slice(0, 5)) F = L.links[0].href, k =
                        B(F); return [k, F, b]
                } function I(k) { var F = k.length; "." === k.charAt(--F) && (k = k.slice(0, F)); "*." === k.slice(0, 2) && (k = k.slice(1)); return k } function n(k) { k = k && k.text ? k.text : k; if (!y(k)) { var F = L.getElementsByTagName("title"); F && d(F[0]) && (k = F[0].text) } return k } function x(k, F) { if (F) return F; "piwik.php" === k.slice(-9) && (k = k.slice(0, k.length - 9)); return k } function D(k) {
                    var F = /index\.php\?module=Overlay&action=startOverlaySession&idsite=([0-9]+)&period=([^&]+)&date=([^&]+)$/.exec(L.referrer); if (F) {
                        if (F[1] !== String(k)) return !1;
                        J.name = "Piwik_Overlay###" + F[2] + "###" + F[3]
                    } k = J.name.split("###"); return 3 === k.length && "Piwik_Overlay" === k[0]
                } function H(k, F, b) { var c = J.name.split("###"), g = c[1], z = c[2], f = x(k, F); r(f + "plugins/Overlay/client/client.js?v=1", function () { Piwik_Overlay_Client.initialize(f, b, g, z) }) } function S(k, F) {
                    function b(a, e, q, E, O, ea) { if (!xa) { var P; q && (P = new Date, P.setTime(P.getTime() + q)); L.cookie = a + "=" + T(e) + (q ? ";expires=" + P.toGMTString() : "") + ";path=" + (E || "/") + (O ? ";domain=" + O : "") + (ea ? ";secure" : "") } } function c(a) {
                        return xa ?
                            0 : (a = RegExp("(^|;)[ ]*" + a + "=([^;]*)").exec(L.cookie)) ? Aa(a[2]) : 0
                    } function g(a) { var e; return Hb ? (e = /#.*/, a.replace(e, "")) : a } function z(a) { var e; for (e = 0; e < Wa.length; e++) { var q = I(Wa[e].toLowerCase()); if (a === q) return !0; if ("." === q.slice(0, 1)) { if (a === q.slice(1)) return !0; var E = a.length - q.length; if (0 < E && a.slice(E) === q) return !0 } } return !1 } function f(a) {
                        var e = document.createElement("script"); e.type = "text/javascript"; e.async = !0; e.src = Ma + (0 > Ma.indexOf("?") ? "?" : "&") + a; e.onload = function () { }; a = document.getElementsByTagName("script")[0];
                        a.parentNode.insertBefore(e, a)
                    } function N(a) { try { var e = J.XMLHttpRequest ? new J.XMLHttpRequest : J.ActiveXObject ? new ActiveXObject("Microsoft.XMLHTTP") : null; e.open("POST", Ma, !0); e.onreadystatechange = function () { 4 === this.readyState && 200 !== this.status && f(a) }; e.setRequestHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8"); e.send(a) } catch (q) { f(a) } } function C(a, e) { var q = new Date; jb || ("POST" === Ib ? N(a) : f(a), Z = q.getTime() + e) } function R() {
                        if (xa) return "0"; if (!d(V.cookieEnabled)) {
                            var a = fa + "testcookie";
                            b(a, "1"); return "1" === c(a) ? "1" : "0"
                        } return V.cookieEnabled ? "1" : "0"
                    } function ia() { Jb((oa || kb) + (pa || "/")).slice(0, 4) } function ca() { var a = c(fa + "cvar"); return a.length && (a = JSON2.parse(a), l(a)) ? a : {} } function W() { lb = (new Date).getTime() } function sa() { var a = Math.round((new Date).getTime() / 1E3), e = c(fa + "id"); e ? (a = e.split("."), a.unshift("0")) : (mb || (mb = Jb((V.userAgent || "") + (V.platform || "") + JSON2.stringify(qa) + a).slice(0, 16)), a = ["1", mb, a, 0, a, "", ""]); return a } function ta() {
                        var a = c(fa + "ref"); if (a.length) try {
                            if (a =
                                JSON2.parse(a), l(a)) return a
                        } catch (e) { } return ["", "", 0, ""]
                    } function U() { var a = xa; xa = !1; b(fa + "id", "", -86400, pa, oa); b(fa + "ses", "", -86400, pa, oa); b(fa + "cvar", "", -86400, pa, oa); b(fa + "ref", "", -86400, pa, oa); xa = a } function M(a, e, q, E) {
                        var O = new Date, ea = Math.round(O.getTime() / 1E3), P = da, Na = fa + "ses", nb = fa + "ref", Xa = fa + "cvar", Q = sa(), Ya = c(Na), Ja = ta(), ob = Za || Kb; xa && U(); if (jb) return ""; var bc = Q[0], Lb = Q[1], Mb = Q[2], pb = Q[3], $a = Q[4], qb = Q[5]; d(Q[6]) || (Q[6] = ""); Q = Q[6]; d(E) || (E = ""); var Oa = L.characterSet || L.charset; Oa && "utf-8" !==
                            Oa.toLowerCase() || (Oa = null); var Ba = Ja[0], Pa = Ja[1], rb = Ja[2], Ca = Ja[3]; if (!Ya) { pb++; qb = $a; if (!sb || !Ba.length) { for (Y in ab) if (Object.prototype.hasOwnProperty.call(ab, Y) && (Ba = t(ob, ab[Y]), Ba.length)) break; for (Y in bb) if (Object.prototype.hasOwnProperty.call(bb, Y) && (Pa = t(ob, bb[Y]), Pa.length)) break } $a = B(Qa); Ya = Ca.length ? B(Ca) : ""; !$a.length || z($a) || sb && Ya.length && !z(Ya) || (Ca = Qa); if (Ca.length || Ba.length) rb = ea, Ja = [Ba, Pa, rb, g(Ca.slice(0, 1024))], b(nb, JSON2.stringify(Ja), Nb, pa, oa) } a += "&idsite=" + cb + "&rec=1&r=" + String(Math.random()).slice(2,
                                8) + "&h=" + O.getHours() + "&m=" + O.getMinutes() + "&s=" + O.getSeconds() + "&url=" + T(g(ob)) + (Qa.length ? "&urlref=" + T(g(Qa)) : "") + "&_id=" + Lb + "&_idts=" + Mb + "&_idvc=" + pb + "&_idn=" + bc + (Ba.length ? "&_rcn=" + T(Ba) : "") + (Pa.length ? "&_rck=" + T(Pa) : "") + "&_refts=" + rb + "&_viewts=" + qb + (String(Q).length ? "&_ects=" + Q : "") + (String(Ca).length ? "&_ref=" + T(g(Ca.slice(0, 1024))) : "") + (Oa ? "&cs=" + T(Oa) : "") + (c("myvne_user_id").length ? "&myvne_user_id=" + c("myvne_user_id") : "") + (c("fosp_vid").length ? "&fosp_vid=" + c("fosp_vid") : ""); O = JSON2.stringify(Da);
                        2 < O.length && (a += "&cvar=" + T(O)); for (Y in qa) Object.prototype.hasOwnProperty.call(qa, Y) && (a += "&" + Y + "=" + qa[Y]); e ? a += "&data=" + T(JSON2.stringify(e)) : ya && (a += "&data=" + T(JSON2.stringify(ya))); if (da) { e = JSON2.stringify(da); 2 < e.length && (a += "&_cvar=" + T(e)); for (Y in P) Object.prototype.hasOwnProperty.call(P, Y) && ("" !== da[Y][0] && "" !== da[Y][1] || delete da[Y]); b(Xa, JSON2.stringify(da), tb, pa, oa) } ub && vb ? a += "&gt_ms=" + vb : ub && ba && ba.timing && ba.timing.requestStart && ba.timing.responseEnd && (a += "&gt_ms=" + (ba.timing.responseEnd -
                            ba.timing.requestStart)); var Y = pb; E = d(E) && String(E).length ? E : Q; b(fa + "id", Lb + "." + Mb + "." + Y + "." + ea + "." + qb + "." + E, Ob, pa, oa); b(Na, "*", tb, pa, oa); a += A(q); wb.length && (a += "&" + wb); xb && (a += "&fosp_id=" + xb); yb && (a += "&fosp_loc=" + yb); return a
                    } function Va(a, e, q, E, O, ea) {
                        var P = "idgoal=0", Na, nb = new Date, Xa = [], Q; String(a).length && (P += "&ec_id=" + T(a), Na = Math.round(nb.getTime() / 1E3)); P += "&revenue=" + e; String(q).length && (P += "&ec_st=" + q); String(E).length && (P += "&ec_tx=" + E); String(O).length && (P += "&ec_sh=" + O); String(ea).length &&
                            (P += "&ec_dt=" + ea); if (aa) { for (Q in aa) Object.prototype.hasOwnProperty.call(aa, Q) && (d(aa[Q][1]) || (aa[Q][1] = ""), d(aa[Q][2]) || (aa[Q][2] = ""), d(aa[Q][3]) && 0 !== String(aa[Q][3]).length || (aa[Q][3] = 0), d(aa[Q][4]) && 0 !== String(aa[Q][4]).length || (aa[Q][4] = 1), Xa.push(aa[Q])); P += "&ec_items=" + T(JSON2.stringify(Xa)) } P = M(P, ya, "ecommerce", Na); C(P, Ea)
                    } function ua(a, e) {
                        var q = new Date, E = M("action_name=" + T(n(a || Pb)), e, "log"); C(E, Ea); zb && Ra && !Qb && (Qb = !0, w(L, "click", W), w(L, "mouseup", W), w(L, "mousedown", W), w(L, "mousemove",
                            W), w(L, "mousewheel", W), w(J, "DOMMouseScroll", W), w(J, "scroll", W), w(L, "keypress", W), w(L, "keydown", W), w(L, "keyup", W), w(J, "resize", W), w(J, "focus", W), w(J, "blur", W), lb = q.getTime(), setTimeout(function ea() { var P = new Date; lb + Ra > P.getTime() && (zb < P.getTime() && (P = M("ping=1", e, "ping"), C(P, Ea)), setTimeout(ea, Ra)) }, Ra))
                    } function La(a, e, q) { a = M(e + "=" + T(g(a)), q, "link"); C(a, Ea) } function va(a) {
                        var e, q, E = ["", "webkit", "ms", "moz"], O; if (!Rb) for (q = 0; q < E.length; q++)if (O = E[q], Object.prototype.hasOwnProperty.call(L, "" !== O ? O +
                            "Hidden" : "hidden")) { "prerender" === L["" !== O ? O + "VisibilityState" : "visibilityState"] && (e = !0); break } e ? w(L, O + "visibilitychange", function P() { L.removeEventListener(O + "visibilitychange", P, !1); a() }) : a()
                    } function ma(a, e) { var q, E = "(^| )(piwik[_-]" + e; if (a) for (q = 0; q < a.length; q++)E += "|" + a[q]; return RegExp(E + ")( |$)") } function na(a) {
                        for (var e, q, E; null !== (q = a.parentNode) && d(q) && "A" !== (E = a.tagName.toUpperCase()) && "AREA" !== E;)a = q; if (d(a.href) && (q = a.hostname || B(a.href), e = q.toLowerCase(), q = a.href.replace(q, e), !/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(q))) {
                            a =
                            a.className; E = q; e = z(e); var O = ma(Sb, "download"), ea = ma(Tb, "link"), P = RegExp("\\.(" + Ab + ")([?&#]|$)", "i"); if (a = ea.test(a) ? "link" : O.test(a) || P.test(E) ? "download" : e ? 0 : "link") q = la(q), La(q, a)
                        }
                    } function Bb(a) { a = a || J.event; var e = a.which || a.button, q = a.target || a.srcElement; "click" === a.type ? q && na(q) : "mousedown" === a.type ? 1 !== e && 2 !== e || !q ? db = eb = null : (db = e, eb = q) : "mouseup" === a.type && (e === db && q === eb && na(q), db = eb = null) } function Ub(a, e) { e ? (w(a, "mouseup", Bb, !1), w(a, "mousedown", Bb, !1)) : w(a, "click", Bb, !1) } function Vb(a) {
                        if (!Wb) {
                            Wb =
                            !0; var e, q = ma(Xb, "ignore"), E = L.links; if (E) for (e = 0; e < E.length; e++)q.test(E[e].className) || Ub(E[e], a)
                        }
                    } var xb = null, yb = null, fb = {}, Cb = G(L.domain, J.location.href, m()), kb = I(Cb[0]), Kb = Cb[1], Qa = Cb[2], Ib = "GET", Ma = k || "", Yb = "", wb = "", cb = F || "", Za, Pb = L.title, Ab = "7z|aac|ar[cj]|as[fx]|avi|bin|csv|deb|dmg|docx?|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|ms[ip]|od[bfgpst]|og[gv]|pdf|phps|png|pptx?|qtm?|ra[mr]?|rpm|sea|sit|tar|t?bz2?|tgz|torrent|txt|wav|wm[av]|wpd||xlsx?|xml|z|zip", Wa = [kb], Xb = [], Sb =
                        [], Tb = [], Ea = 500, zb, Ra, Hb, ya, ab = ["pk_campaign", "piwik_campaign", "utm_campaign", "utm_source", "utm_medium"], bb = ["pk_kwd", "piwik_kwd", "utm_term"], fa = "_pk_", oa, pa, xa = !1, jb, Rb, sb, Ob = 63072E6, tb = 18E5, Nb = 15768E6, ub = !0, vb = 0, da = !1, Da = {}, aa = {}, qa = {}, Wb = !1, Qb = !1, lb, db, eb, Jb = Ua, mb; (function () {
                            var a, e, q = {
                                pdf: "application/pdf", qt: "video/quicktime", realp: "audio/x-pn-realaudio-plugin", wma: "application/x-mplayer2", dir: "application/x-director", fla: "application/x-shockwave-flash", java: "application/x-java-vm", gears: "application/x-googlegears",
                                ag: "application/x-silverlight"
                            }, E = /Mac OS X.*Safari\//.test(V.userAgent) ? J.devicePixelRatio || 1 : 1; if (!/MSIE/.test(V.userAgent)) { if (V.mimeTypes && V.mimeTypes.length) for (a in q) Object.prototype.hasOwnProperty.call(q, a) && (e = V.mimeTypes[q[a]], qa[a] = e && e.enabledPlugin ? "1" : "0"); "unknown" !== typeof navigator.javaEnabled && d(V.javaEnabled) && V.javaEnabled() && (qa.java = "1"); "function" === typeof J.GearsFactory && (qa.gears = "1"); qa.cookie = R() } qa.res = ha.width * E + "x" + ha.height * E
                        })(); ia(); A("run", function (a, e) {
                            var q = null;
                            if (y(a) && !d(fb[a]) && e) { if (l(e)) q = e; else if (y(e)) try { eval("hookObj =" + e) } catch (E) { } fb[a] = q } return q
                        }); return {
                            hook: fb, getHook: function (a) { return fb[a] }, getVisitorId: function () { return sa()[1] }, getVisitorInfo: function () { return sa() }, getAttributionInfo: function () { return ta() }, getAttributionCampaignName: function () { return ta()[0] }, getAttributionCampaignKeyword: function () { return ta()[1] }, getAttributionReferrerTimestamp: function () { return ta()[2] }, getAttributionReferrerUrl: function () { return ta()[3] }, setTrackerUrl: function (a) {
                                Ma =
                                a
                            }, setSiteId: function (a) { cb = a }, setCustomData: function (a, e) { l(a) ? ya = a : (ya || (ya = []), ya[a] = e) }, appendToTrackingUrl: function (a) { wb = a }, getCustomData: function () { return ya }, setCustomVariable: function (a, e, q, E) { d(E) || (E = "visit"); if (0 < a) if (e = d(e) && !y(e) ? String(e) : e, q = d(q) && !y(q) ? String(q) : q, e = [e.slice(0, 200), q.slice(0, 200)], "visit" === E || 2 === E) !1 === da && (da = ca()), da[a] = e; else if ("page" === E || 3 === E) Da[a] = e }, getCustomVariable: function (a, e) {
                                d(e) || (e = "visit"); if ("page" === e || 3 === e) var q = Da[a]; else if ("visit" === e ||
                                    2 === e) !1 === da && (da = ca()), q = da[a]; return !d(q) || q && "" === q[0] ? !1 : q
                            }, deleteCustomVariable: function (a, e) { this.getCustomVariable(a, e) && this.setCustomVariable(a, "", "", e) }, setLinkTrackingTimer: function (a) { Ea = a }, setDownloadExtensions: function (a) { Ab = a }, addDownloadExtensions: function (a) { Ab += "|" + a }, setDomains: function (a) { Wa = y(a) ? [a] : a; Wa.push(kb) }, setIgnoreClasses: function (a) { Xb = y(a) ? [a] : a }, setRequestMethod: function (a) { Ib = a || "GET" }, setReferrerUrl: function (a) { Qa = a }, setFospId: function (a) { xb = a }, setLocation: function (a) {
                                yb =
                                a
                            }, setCustomUrl: function (a) { var e = Kb, q; u(a) ? Za = a : "/" === a.slice(0, 1) ? Za = u(e) + "://" + B(e) + a : (e = g(e), 0 <= (q = e.indexOf("?")) && (e = e.slice(0, q)), (q = e.lastIndexOf("/")) !== e.length - 1 && (e = e.slice(0, q + 1)), Za = e + a) }, setDocumentTitle: function (a) { Pb = a }, setAPIUrl: function (a) { Yb = a }, setDownloadClasses: function (a) { Sb = y(a) ? [a] : a }, setLinkClasses: function (a) { Tb = y(a) ? [a] : a }, setCampaignNameKey: function (a) { ab = y(a) ? [a] : a }, setCampaignKeywordKey: function (a) { bb = y(a) ? [a] : a }, discardHashTag: function (a) { Hb = a }, setCookieNamePrefix: function (a) {
                                fa =
                                a; da = ca()
                            }, setCookieDomain: function (a) { oa = I(a); ia() }, setCookiePath: function (a) { pa = a; ia() }, setVisitorCookieTimeout: function (a) { Ob = 1E3 * a }, setSessionCookieTimeout: function (a) { tb = 1E3 * a }, setReferralCookieTimeout: function (a) { Nb = 1E3 * a }, setConversionAttributionFirstReferrer: function (a) { sb = a }, disableCookies: function () { xa = !0; qa.cookie = "0" }, deleteCookies: function () { U() }, setDoNotTrack: function (a) { var e = V.doNotTrack || V.msDoNotTrack; (jb = a && ("yes" === e || "1" === e)) && this.disableCookies() }, addListener: function (a, e) {
                                Ub(a,
                                    e)
                            }, enableLinkTracking: function (a) { ka ? Vb(a) : za.push(function () { Vb(a) }) }, disablePerformanceTracking: function () { ub = !1 }, setGenerationTimeMs: function (a) { vb = parseInt(a, 10) }, setHeartBeatTimer: function (a, e) { zb = (new Date).getTime() + 1E3 * a; Ra = 1E3 * e }, killFrame: function () { J.location !== J.top.location && (J.top.location = J.location) }, redirectFile: function (a) { "file:" === J.location.protocol && (J.location = a) }, setCountPreRendered: function (a) { Rb = a }, trackGoal: function (a, e, q) {
                                va(function () {
                                    var E = M("idgoal=" + a + (e ? "&revenue=" +
                                        e : ""), q, "goal"); C(E, Ea)
                                })
                            }, trackLink: function (a, e, q) { va(function () { La(a, e, q) }) }, trackPageView: function (a, e) { D(cb) ? va(function () { H(Ma, Yb, cb) }) : va(function () { ua(a, e) }) }, trackSiteSearch: function (a, e, q) { va(function () { var E = M("search=" + T(a) + (e ? "&search_cat=" + T(e) : "") + (d(q) ? "&search_count=" + q : ""), void 0, "sitesearch"); C(E, Ea) }) }, setEcommerceView: function (a, e, q, E) {
                                d(q) && q.length ? q instanceof Array && (q = JSON2.stringify(q)) : q = ""; Da[5] = ["_pkc", q]; d(E) && String(E).length && (Da[2] = ["_pkp", E]); if (d(a) && a.length ||
                                    d(e) && e.length) d(a) && a.length && (Da[3] = ["_pks", a]), d(e) && e.length || (e = ""), Da[4] = ["_pkn", e]
                            }, addEcommerceItem: function (a, e, q, E, O) { a.length && (aa[a] = [a, e, q, E, O]) }, trackEcommerceOrder: function (a, e, q, E, O, ea) { String(a).length && d(e) && Va(a, e, q, E, O, ea) }, trackEcommerceCartUpdate: function (a) { d(a) && Va("", a, "", "", "", "") }
                        }
                } var Z, wa = {}, L = document, V = navigator, ha = screen, J = window, ba = J.performance || J.mozPerformance || J.msPerformance || J.webkitPerformance, ka = !1, za = [], T = J.encodeURIComponent, Aa = J.decodeURIComponent, la = unescape,
                    K; w(J, "beforeunload", function () { A("unload"); if (Z) { do var k = new Date; while (k.getTimeAlias() < Z) } }, !1); (function () {
                        var k; L.addEventListener ? w(L, "DOMContentLoaded", function b() { L.removeEventListener("DOMContentLoaded", b, !1); p() }) : L.attachEvent && (L.attachEvent("onreadystatechange", function c() { "complete" === L.readyState && (L.detachEvent("onreadystatechange", c), p()) }), L.documentElement.doScroll && J === J.top && function g() { if (!ka) { try { L.documentElement.doScroll("left") } catch (z) { setTimeout(g, 0); return } p() } }());
                        /WebKit/.test(V.userAgent) && (k = setInterval(function () { if (ka || /loaded|complete/.test(L.readyState)) clearInterval(k), p() }, 10)); w(J, "load", p, !1)
                    })(); Date.prototype.getTimeAlias = Date.prototype.getTime; var ra = new S; for (K = 0; K < _paq.length; K++)if ("setTrackerUrl" === _paq[K][0] || "setSiteId" === _paq[K][0]) h(_paq[K]), delete _paq[K]; for (K = 0; K < _paq.length; K++)_paq[K] && h(_paq[K]); _paq = new function () { return { push: h } }; var X = { addPlugin: function (k, F) { wa[k] = F }, getTracker: function (k, F) { return new S(k, F) }, getAsyncTracker: function () { return ra } };
                "function" === typeof define && define.amd && define(["piwik"], [], function () { return X }); return X
            }()); "function" !== typeof piwik_log && (piwik_log = function (d, l, y, h) {
                function w(p) { try { return eval("piwik_" + p) } catch (r) { } } var A = PiwikNew.getTracker(y, l); A.setDocumentTitle(d); A.setCustomData(h); (d = w("tracker_pause")) && A.setLinkTrackingTimer(d); (d = w("download_extensions")) && A.setDownloadExtensions(d); (d = w("hosts_alias")) && A.setDomains(d); (d = w("ignore_classes")) && A.setIgnoreClasses(d); A.trackPageView(); w("install_tracker") &&
                    (piwik_track = function (p, r, m, u) { A.setSiteId(r); A.setTrackerUrl(m); A.trackLink(p, u) })
            }); var Db = new Gb(ja); window.callback_ea = function (d) { }; Db = (window.FospAnalyticsNew = Db) || new Gb(ja); try { Db.logData(window._siteId) } catch (d) { } (function (d, l, y, h) {
                var w = d.encodeURIComponent, A = d.decodeURIComponent, p = navigator, r = function (b, c) { var g = new XMLHttpRequest; g.open("GET", b, !0); g.responseType = "json"; g.onload = function () { var z = g.status; 200 === z ? c(null, g.response) : c(z, g.response) }; g.onerror = function () { c("error", {}) }; g.send() },
                m = function (b) { return (b = (new RegExp("(^|;)[ ]*" + b + "=([^;]*)")).exec(l.cookie)) ? A(b[2]) : "" }, u = function (b, c, g, z) {
                    var f = document.domain.split("."); !g && (g = 0); !z && (z = 31449600); if (1 < f.length && c) for (var N = "." + f[f.length - 1], C = f.length - 2; 0 <= C; C--) {
                        N = "." + f[C] + N; var R = void 0, ia = b, ca = c, W = z, sa = N; W && (R = new Date, R.setTime(R.getTime() + 1E3 * W)); l.cookie = ia + "=" + w(ca) + (W ? ";expires=" + R.toGMTString() : "") + ";path=/" + (sa ? ";domain=" + sa : ""); if (m(b) == c) {
                            0 == g && (g = window, f = window.name, N = b, C = c, -1 < f.indexOf("&" + N + "=") || 0 === f.indexOf(N +
                                "=") ? (R = f.indexOf("&" + N + "="), -1 === R && (R = f.indexOf(N + "=")), z = f.indexOf("&", R + 1), z = -1 !== z ? f.substr(0, R) + f.substr(z + (R ? 0 : 1)) + "&" + N + "=" + C : f.substr(0, R) + "&" + N + "=" + C) : z = f + "&" + N + "=" + C, g.name = z, Ia(b, c, 0)); break
                        }
                    }
                }; h = function () { r("https://g.eclick.vn/iplookup", function (b, c) { "" == m("fosp_loc") && c.data && c.data.country_code && (n = [c.data.province_id, c.data.region_id, c.data.country_code].join("-"), u("fosp_loc", n, 0, 86400)) }) }; a: { if (p = this.navigator) if (y = p.userAgent) { var B = y; break a } B = "" } var t = function (b) {
                    return -1 !=
                        B.toLowerCase().indexOf(b.toLowerCase())
                }, G = function () { return t("iPad") || t("Android") && !t("Mobile") || t("Silk") }, I = function () { return /Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|NetFront|Silk-Accelerated|(hpw|web)OS|Fennec|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Dolphin|Skyfire|Zune/i.test(B) }, n = m("fosp_loc"); "" == n && h(); var x = function (b) {
                    var c = m(b) || "", g = (new RegExp("(^|&)[ ]*" + b + "=([^&]*)", "i")).exec(window.name); g = g && 2 < g.length && window.decodeURIComponent(g[2]) || ""; b = Ga(b); return c || b ||
                        g
                }, D = "---", H = function () { for (var b = "", c = 0; 16 > c; c++)b += "abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(36 * Math.random())); c = I() ? "mob" : G() ? "tab" : "des"; return b + "." + Math.floor((new Date).getTime() / 1E3) + "." + c }; h = function (b) {
                    if (l.cookie != D || 2 == b) {
                        D = l.cookie; var c = parseInt("0" + m("myvne_user_id")) || 0, g = m("fosp_aid"), z = m("orig_aid"); b = x("fosp_aid") || ""; var f = x("orig_aid") || ""; if (1E4 < c) g != c && (u("fosp_aid", c), g != z && (f = 12 < b.length ? b : 12 < f.length ? f : H(), u("orig_aid", f))); else if ("" != b && b == parseInt("0" +
                            b)) u("fosp_aid", f); else if ("" != f && f != parseInt("0" + f)) u("fosp_aid", f), u("orig_aid", f); else if (g != z || "" == g || "" == z) c = 12 < b.length ? b : 12 < f.length ? f : H(), b != c && u("fosp_aid", c), f != c && u("orig_aid", c)
                    }
                }; "undefined" == typeof window.FospAnalyticsNew && (d.setInterval(h, 1E3), h(2)); var S = !1, Z = d._logEgg || (d._logEgg = []); h = d.PAGE_DETAIL || 0; var wa = function (b, c, g) { return b.call.apply(b.bind, arguments) }, L = function (b, c, g) {
                    if (!b) throw Error(); if (2 < arguments.length) {
                        var z = Array.prototype.slice.call(arguments, 2); return function () {
                            var f =
                                Array.prototype.slice.call(arguments); Array.prototype.unshift.apply(f, z); return b.apply(c, f)
                        }
                    } return function () { return b.apply(c, arguments) }
                }, V = function (b) { try { b = "string" !== typeof b ? JSON.stringify(b) : b } catch (c) { return "" } return b }, ha = function (b, c, g) { ha = Function.prototype.bind && -1 != Function.prototype.bind.toString().indexOf("native code") ? wa : L; return ha.apply(null, arguments) }, J = function (b, c, g, z) { b.addEventListener ? b.addEventListener(c, g, !!z) : b.attachEvent ? b.attachEvent("on" + c, g) : b["on" + c] = g }, ba = function (b,
                    c, g, z) { b.removeEventListener ? b.removeEventListener(c, g, !!z) : b.detachEvent ? b.detachEvent("on" + c, g) : b["on" + c] = null }, ka = function (b) { var c = /^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(b); return c ? c[1] : b }, za = function (b, c) { var g = new Image(1, 1); if (c) { var z = function (f) { c(f); ba(g, "load", z, !1); ba(g, "error", z, !1) }; J(g, "load", z, !1); J(g, "error", z, !1) } g.src = b }; y = function (b) {
                        var c; l.addEventListener ? J(l, "DOMContentLoaded", function z() { ba(l, "DOMContentLoaded", z, !1); b() }, !1) : l.attachEvent && (J(l, "onreadystatechange",
                            function f() { "complete" === l.readyState && (ba(l, "onreadystatechange", f, !1), b()) }, !1), l.documentElement.doScroll && d === d.top && function N() { if (!S) { try { l.documentElement.doScroll("left") } catch (C) { setTimeout(N, 0); return } b() } }()); /WebKit/.test(p.userAgent) && (c = setInterval(function () { if (S || /loaded|complete/.test(l.readyState)) clearInterval(c), b() }, 10)); J(d, "load", b, !1)
                    }; var T = function (b) { var c = {}, g; for (g in b) if (b.hasOwnProperty(g)) { var z = b[g], f = typeof z; c[g] = "function" === f || "object" === f && z ? T(b[g]) : b[g] } return c },
                        Aa = function (b) { return null === b ? !1 : "function" === typeof b || "object" === typeof b }, la = function () {
                            this.version = "1404"; this.location_url = d.location_url || d.location.href; this.site_id = parseInt("0" + d.SITE_ID); this.pageview_id = this.my_vne = this.fosp_loc = this.fosp_aid = this.uid = null; this.meta = {}; this.dataLayer = {}; this.video_id = this.article_id = 0; this.action_name = "profile_update play pageview buy addtocart checkout read like comment save fblike fbshare twitter ggplus".split(" "); this.action = "pageview"; this.host =
                                this.referer = this.link_ref = null; this.platform = "1"; this.algoRead = this.totalRead = this.readStart = 0; this.intervalScroll = this.intervalEvent = !1; this.readView = this.scrollView = 0; this.timeEvent = 2E3; this.intervalCount = 0; this.container = null; this.wordCount = 0; this.type = "text"; this.playEmbed = 0; this.logEggType = { ts_10: 0, ts_20: 0, ts_25: 0, ts_30: 0, ts_40: 0, ts_50: 0, ts_60: 0, ts_70: 0, ts_75: 0, ts_80: 0, ts_90: 0, ts_100: 0 }; this.vnTracking = function () {
                                    for (var b = d.dataLayer || {}, c = 0; c < b.length; c++) {
                                        var g = b[c], z; for (z in g) if ("vn_source" ==
                                            z || "vn_campaign" == z || "vn_medium" == z || "vn_zone" == z) this.meta[z] = g[z]
                                    }
                                }; this.init = function () {
                                    var b = x("fosp_aid"), c = x("orig_aid"); if (!b || "" == b || "null" == b) { var g; b = (g = /(^|&)[ ]*fosp_aid=([^&]*)/.exec(d.name)) ? A(g[2]) : H() } this.fosp_aid = b.substr(0, 40); this.uid = c ? c.substr(0, 40) : this.fosp_aid; this.fosp_loc = n; this.my_vne = m("myvne_user_id"); this.pageview_id = window.la_pageview_id && "" != window.la_pageview_id ? window.la_pageview_id : Ua(Math.random() + this.fosp_aid + Date.now()).substr(0, 32); g = {}; b = l.getElementsByTagName("meta");
                                    c = 0; for (var z = b.length, f = b[c]; c < z; f = b[++c]) { var N = f.getAttribute("name"); f = f.getAttribute("content"); null != N && (g[N] = f) } this.meta = g; this.article_id = this.meta.its_id || 0; this.video_id = this.meta.its_video_id || 0; this.ref_id = this.meta.its_ref || 0; g = ""; try { g = d.top.document.referrer } catch (R) { if (d.parent) try { g = d.parent.document.referrer } catch (ia) { g = "" } } "" === g && (g = l.referrer); this.link_ref = g; this.referer = ka(g); this.host = ka(d.location.href); I() ? this.platform = "2" : G() && (this.platform = "3"); this.meta.hasOwnProperty("its_type") &&
                                        (this.type = this.meta.its_type || "text"); c = b = 0; g = ""; if ("object" == typeof d.dataLayer) for (z = 0; z < d.dataLayer.length; z++) { f = d.dataLayer[z]; for (var C in f) "TaxonomyIndexType" == C && "" != f[C] && (g = f[C]), "TaxonomySubTopicId" == C && "" != f[C] && (b = f[C]), "TaxonomyIndexFormatId" == C && "" != f[C] && (c = f[C]) } this.dataLayer = { index_topic: b, index_format: c, index_type: g }; this.vnTracking()
                                }; this.eventBeforeUnLoad = function (b) { d.setTimeout(ha(this.actualRead, this), 0); return !0 }; this.actualRead = function () {
                                    var b = Date.now(); if (0 < this.readStart) {
                                        this.algoRead +=
                                        b - this.readStart; this.algoRead = Math.min(this.algoRead, this.totalRead); var c = Math.min(100, Math.floor(100 * this.algoRead / this.totalRead)); c = 10 * Math.floor(c / 10); c > this.readView && (this.readView = c); c = Math.min(this.readView, this.scrollView); var g = "ts_" + c; !this.logEggType[g] && (this.logEggType[g] = 1, this.sendLog({ action: "read", ratio: c, pv_read: this.algoRead, pv_scroll: this.scrollView, pv_total: this.totalRead })); c = V({
                                            pv_v: this.version, pv_action: "read", pv_type: "article", pv_ratio: this.readView, pv_scroll: this.scrollView,
                                            pv_time: this.algoRead
                                        }); d.postMessage(c, "*"); 91 < c && (this.intervalEvent && d.clearTimeout(this.intervalEvent), ba(d, "scroll", ra, !1))
                                    } this.readStart = b
                                }; this.eventVideo = function (b) {
                                    if (b.detail && b.detail.type) {
                                        var c = 0; switch (b.detail.type) { case "videoComplete": c = 100; break; case "videoStart": c = 0; break; case "videoPlay": c = 0; break; case "videoProgress": c = ("" + (b.detail && b.detail.percent)).replace("%", ""), c = 1 * parseInt(c) }this.logEggType.hasOwnProperty("ts_" + c) && !this.logEggType["ts_" + c] && (this.logEggType["ts_" +
                                            c] = 1, this.sendLog({ action: "play", type: "video", ratio: c })); b = V({ pv_v: this.version, pv_action: "play", pv_type: "video", pv_ratio: c }); d.postMessage(b, "*")
                                    }
                                }; this.eventInterval = function () {
                                    if ("video" == this.type || "play" == this.action) return !1; var b = !0; this.actualRead(); 6 > this.intervalCount ? 0 < this.readStart && (this.intervalEvent && d.clearTimeout(this.intervalEvent), this.intervalEvent = d.setTimeout(ha(this.eventInterval, this), 1E4)) : (this.intervalEvent && d.clearTimeout(this.intervalEvent), this.intervalEvent = null, b =
                                        !1); b || (this.readStart = 0); this.intervalCount += 1
                                }; this.eventScroll = function () { this.intervalScroll && (d.clearTimeout(this.intervalScroll), this.intervalEvent && d.clearTimeout(this.intervalEvent)); this.intervalScroll = d.setTimeout(ha(this.intervalScrollFunc, this), this.timeEvent) }; this.intervalScrollFunc = function () {
                                    var b = !1; if (this.container) {
                                        var c = this.container.getBoundingClientRect(); c && 0 < c.height && (c.top < d.innerHeight && 0 < c.bottom && (b = !0), c.top < d.innerHeight && 0 < c.bottom ? b = !0 : this.readStart = 0, c = 100 - 100 *
                                            (c.bottom - d.innerHeight) / c.height, c = 95 < c ? 100 : 85 < c && 95 > c ? 90 : 75 < c && 85 > c ? 80 : 65 < c && 75 > c ? 70 : 55 < c && 65 > c ? 60 : 45 < c && 55 > c ? 50 : 35 < c && 45 > c ? 40 : 25 < c && 35 > c ? 30 : 15 < c && 25 > c ? 20 : 10, this.scrollView < c && (this.scrollView = c, c = V({ pv_v: this.version, pv_action: "read", pv_type: "article", pv_ratio: this.readView, pv_scroll: this.scrollView, pv_time: this.algoRead }), d.postMessage(c, "*")))
                                    } b && (this.intervalCount = 0, this.eventInterval())
                                }; this.initReady = function () {
                                    var b = this.meta.hasOwnProperty("its_wordcount") && parseInt(this.meta.its_wordcount,
                                        10) || 0; if ("video" == this.type || "play" == this.action) this.scrollView = 100, this.totalRead = 0 < b ? 1E3 * b : 0, J(d, "PlayerCustomEvent", ha(this.eventVideo, this), !1); else {
                                            var c = function (ca) { return null === ca.replace(/\s+/g, "").match(/([^\x00-\x7F\u2013\u2014])+/gi) == 0 ? ca.match(/\S+/g) : ca.replace(/[;!:\u2014\/]/g, " ").replace(/\.\s+/g, " ").replace(/[^a-zA-Z\d\s&:,]/g, "").replace(/,([^0-9])/g, " $1").match(/\S+/g) }, g = "", z = "", f = 0, N = 0; try {
                                                var C = l.getElementsByClassName("description"); 0 < C.length && C[0].innerText ? g = C[0].innerText :
                                                    (C = l.getElementsByClassName("short_intro mb15"), 0 < C.length && C[0].innerText && (g = C[0].innerText))
                                            } catch (ca) { } try {
                                                if (C = l.getElementsByClassName("fck_detail"), 0 == C.length && (C = l.getElementsByClassName("block_ads_connect"), 0 == C.length && (C = l.getElementsByTagName("body"))), 0 < C.length && C[0].innerText) {
                                                    this.container = C[0]; z = this.container.innerText; var R = this.container.getElementsByTagName("img"); if (0 < R.length) for (C = 0; C < R.length; C++)200 < R[C].offsetHeight && 200 < R[C].offsetWidth && (f += 1); var ia = l.getElementsByClassName("list-news");
                                                    0 < ia.length && (N = c(ia[0].innerText || "").length)
                                                }
                                            } catch (ca) { } c = c(g + " " + z).length - N; this.wordCount = Math.max(c, b, 0); b = 0; 0 < f && (b = "photo" == this.type ? 10 * f : 5 * f); this.totalRead = 1E3 * (b + Math.round(this.wordCount / 5.83))
                                        } 1 > this.totalRead && (this.totalRead = 1); this.readStart = Date.now(); this.timeEvent = 2E3; "video" != this.type && this.eventScroll(); b = V({ pv_v: this.version, pv_action: "init_ready", pv_word_count: this.wordCount, pv_total_read: this.totalRead, pv_read_start: this.readStart, pv_data_layer: this.dataLayer }); d.postMessage(b,
                                            void 0)
                                }
                        }; la.prototype.sendLog = function (b) {
                            var c; b.hasOwnProperty("action") && (c = -1 < this.action_name.indexOf(b.action) ? b.action : null); if (c) {
                                for (var g = this.meta, z = "vn_zone vn_source vn_medium vn_campaign its_name its_url its_id its_title its_section its_subsection its_tag its_topic its_object its_embed its_author its_type its_wordcount its_publication".split(" "), f = 0, N = z.length; f < N; f++) { var C = z[f]; g.hasOwnProperty(C) && (b[C] = g[C]) } b.platform = this.platform; b.fosp_loc = this.fosp_loc; b.referer = this.referer;
                                b.link_ref = this.link_ref; b.location_url = this.location_url; b.site_id = this.site_id; g = []; delete b.its_id; delete b.its_ref; for (var R in b) Aa(b[R]) || g.push(R + "=" + w(b[R])); if (1 > this.article_id && -1 < " play pageview buy addtocart checkout read like comment save fblike fbshare twitter ggplus".indexOf(b.action)) return !1; g.push("its_id=" + this.article_id); g.push("its_video_id=" + this.video_id); g.push("its_ref=" + this.ref_id); g.push("fosp_aid=" + this.fosp_aid); g.push("uid=" + this.uid); g.push("my_vne=" + this.my_vne);
                                g.push("play_embed=" + this.playEmbed); g.push("pageview_id=" + this.pageview_id); za("https://la3.vnecdn.net/" + c + "/?" + g.join("&"), function () { }); return !0
                            }
                        }; if (Z.push === Array.prototype.push) {
                            var K = new la; K.init(); if (h) { K.sendLog({ action: "pageview" }); var ra = ha(K.eventScroll, K); y(function () { S || (K.initReady(), J(d, "scroll", ra, !1)); S = !0 }) } else 1003834 == d.SITE_ID && K.sendLog({ action: "pageview" }); var X = {}; X["egg" + K.article_id] = K; var k = function (b) {
                                var c = "play" == b.action ? "play" : "egg", g = b.meta && b.meta.its_id || b.id ||
                                    K.article_id, z = b.meta && b.meta.its_video_id || K.video_id || 0; c = "play" == c ? "play" + z : "egg" + g; if (!(X[c] && X[c] instanceof la)) {
                                        var f = new la; f.action = b.action; f.playEmbed = b.play_embed || 0; f.fosp_aid = K.fosp_aid; f.uid = K.uid; f.fosp_loc = K.fosp_loc; f.my_vne = K.my_vne; f.pageview_id = "pageview" == b.action ? Ua(Math.random() + K.fosp_aid + Date.now()).substr(0, 32) : K.pageview_id; f.meta = T(K.meta); f.article_id = g; f.video_id = z; f.ref_id = K.article_id; f.referer = K.host; f.link_ref = K.link_ref; f.location_url = "pageview" == b.action ? d.location.href :
                                            K.location_url; f.platform = K.platform; if (b.meta && Aa(b.meta)) for (var N in b.meta) f.meta[N] = b.meta[N]; f.vnTracking(); f.type = b.meta && b.meta.its_type ? b.meta.its_type : K.type; for (var C in X) X.hasOwnProperty(C) && X[C] instanceof la && X[C].type == f.type && (X[C].logEggType = {}); f.initReady(); X[c] = f
                                    } return X[c]
                            }; y = function (b) { if ("[object Object]" !== Object.prototype.toString.call(b)) return !1; k(b).sendLog(b); return 1 }; h = 0; for (var F = Z.length; h < F; ++h)y(Z[h]); Z.push = function (b) {
                                k(b).sendLog(b); "pageview" == b.action && b.meta &&
                                    "video" == b.meta.its_type && (b = T(b), b.action = "play", b.ratio = 0, k(b).sendLog(b))
                            }; 1003834 == d.SITE_ID && "pageview" == K.action && "video" == K.type && (h = { action: "play", ratio: 0, meta: { its_video_id: K.video_id } }, k(h).sendLog(h))
                        }
            })(window, document, location, history); (function () {
                var d = function (w) { try { for (var A = "", p = 0; p < w.length; p++)0 != p % 14 && (A += w[p]); return JSON.parse(unescape(A)) } catch (r) { } return {} }; window.adblock = Ha ? Ga("f_adblock") : Sa("f_adblock"); var l = { age: 0, gender: 0, ret: "", segment: [], utime: 0 }, y = Ha ? Ga("f_opt") :
                    Sa("f_opt"), h = (new Date).setHours(6, 0, 0, 0).valueOf() + 864E5 - (new Date).valueOf(); h = Math.round(h / 1E3); "" != y && (l = d(y)); if (!l.utime || l.utime < h) window.ufo8 = function (w) { h += 259200; Ha ? Ia("f_opt", w, h) : Eb("f_opt", w, h); l = d(w) }, y = Sa("orig_aid"), 9 < y.length && 50 > y.length && gb("https://adp.vnecdn.net/fopt.js?aid=" + y, function () { }, function () { }); gb("https://s.eclick.vn/bad.js", function () { }, function () { Ha ? Ia("f_adblock", "1", h) : Eb("f_adblock", "1", h); window.adblock = 1 }); y = window.foptTarget = function () {
                        return {
                            segment: function () {
                                return l.hasOwnProperty("segment") ?
                                    l.segment : []
                            }, retar: function () { return l.hasOwnProperty("ret") ? l.ret : "" }
                        }
                    }(); Array.isArray(y) && (window.dataLayer || []).push({ event: "adp_segment", adp_data: y.join(",") }); window.optTarget = { segment: y.segment() }
            })()
})();